### ISSUE TITLE
Installation of 0.2.1

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#34]
Hey Gaël, just had the issue that `add IndividualDisplacements` insalled v0.1.13 instead of 0.2.1 because there was a compatibility issue with StatsBase, which you have set to 0.33, whereas some older (less frequently maintained) packages I had installed had compat of StatBase restricted to 0.32. Maybe you could change the `Project.toml` to something like `StatsBase = "0.20 - 0.33" if it's compatible? That would prevent users from ending up with v0.1.13 of IndividualDisplacements, which seem to have a quite different API...

**Comment by gaelforget** [comment]
Thanks for pointing this out. As it turns out, the pkg was not using StatsBase anymore (?), so I just removed it from dependencies. Will wait for CI to complete and register 0.2.2 later today

**Comment by milankl** [comment]
https://github.com/openjournals/joss-reviews/issues/2813
