### ISSUE TITLE
Velocity = 🚄?

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#39]
https://github.com/JuliaClimate/IndividualDisplacements.jl/blob/7a5df040c6674013deb461f5fe6bd3feb21d3ba4/src/API.jl#L20

I find it confusing to describe the 🚄 as velocity, whereas from the `/src` it seems to me that this is actually the interpolation function for a given velocity field? Reading through the docs I initially thought that one has to provide the flow fields as 🚄.

**Comment by milankl** [comment]
https://github.com/openjournals/joss-reviews/issues/2813

**Comment by gaelforget** [comment]
I just added a comment in the `docstring` to be more explicit (the quoted line  starts with `functions` but was not enough). The hasted docs also now has this information further repeated (see `typical workflow`, and 2nd `tutorial example`)

**Comment by milankl** [comment]
Sounds good.
