### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#40]
https://github.com/JuliaClimate/IndividualDisplacements.jl/blob/7a5df040c6674013deb461f5fe6bd3feb21d3ba4/src/API.jl#L42

This should be `\:bullettrain_side:`.

**Comment by milankl** [comment]
https://github.com/openjournals/joss-reviews/issues/2813

**Comment by gaelforget** [comment]
Thanks Milan! I should be able to work on the docs (and maybe types) over the week end. Meanwhile I wanted to say that this type of feedback is super helpful

**Comment by gaelforget** [comment]
done
