### ISSUE TITLE
dxy_dt: type stable / flexible?

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#41]
https://github.com/JuliaClimate/IndividualDisplacements.jl/blob/7a5df040c6674013deb461f5fe6bd3feb21d3ba4/src/compute.jl#L19

As far as I understand, here you define the velocity interpolation function which will be passed on to the ODE solver. However, you've defined this function with strong limitations on the type, i.e. `Float64` only. I'd suggest to write these functions for `u::Array{T,1}` with `where {T<:AbstractFloat}` and then introduce `oone = one(T)` and write `(oone-dx)` etc. As you essentially only use arithmetics & floor, you'd end up immediately for a type-flexible function that works for `Float64` as well as `Float32` and anything else.

**Comment by milankl** [comment]
Ah I see, you also pull data from P::NamedTuple ... in that case your `dxy_dt` functions are probably not typle-stable, such that there will be a lot of type checks at runtime when I'm not wrong? As evaluating `dxy_dt` is probably the most costly operation while computing the trajectories, I'd assume that there's loads of room for improvement.

You could for example define a header function that pulls the respective arrays from P and then call `dxy_dt` solely with Julia arrays, which you can easily write type stable.

**Comment by milankl** [comment]
https://github.com/openjournals/joss-reviews/issues/2813

**Comment by milankl** [comment]
Maybe as an addition to that, NamedTuple vs struct:
```julia
julia> h(x::NamedTuple) = x.a + 1.0
h (generic function with 1 method)

julia> struct Test
           a::Float64
       end

julia> h(x::Test) = x.a + 1.0
h (generic function with 2 methods)
```
So `h` has 2 methods, one for NamedTuples and the other one for struct, otherwise they are identical
```julia
julia> using BenchmarkTools
julia> X = (a = 1.0,)     # create a NamedTuple
julia> Y = Test(1.0)     # create a struct
julia> @btime h(X);
  19.129 ns (1 allocation: 16 bytes)

julia> @btime h(Y);
  6.426 ns (1 allocation: 16 bytes)
```
Although `h` is very simple, there's already a 3x speed difference.

**Comment by milankl** [comment]
Just picking this review up again, I guess this is type stability is somewhat optional, but I'd still recommend it for more flexibility.

**Comment by gaelforget** [comment]
Hi @milankl 

Thanks for the feedback and suggestion. 

I implemented it as the abstract type called `FlowFields` in `v0.2.7` (Dec. 2020). It currently comes in four flavors / concrete types: 

```
𝐹_Array2D{T}
𝐹_Array3D{T}
𝐹_MeshArray2D{T}
𝐹_MeshArray3D{T}
```

Doing this (+ a bit more work) did indeed speed up computation the `dxy_dt` etc computations quite a bit. 

The introduction of these data structures also helped with further simplifying the workflow -- e.g. choosing the suitable velocity  interpolation depending on the concrete FlowField type automatically. 

Doing something like this had been near the top on my todo list, I must admit. Thanks again for opening this issue. While this is probably not the last time that an issue will be opened wrt types or performance, maybe we can close this one?

ps. sorry, I should have posted this comment response in Dec. right after doing the code development

**Comment by gaelforget** [comment]
Can close this one too, maybe? Happy to leave it open if needed though

**Comment by milankl** [comment]
Yes, absolutely, I guess the `P::NamedTuple` is purely a performance issue. I believe that growing the `I.🔴` (that's a DataFrame, right?) inside `∫!` is  another bottleneck that one may want to come by. When I created the ShalloWaters example, IndividualDisplacements took about as long as running ShallowWaters -- which shouldn't be the case, I believe. Pre-allocating the memory might already be a big winner there.

**Comment by milankl** [comment]
Anyway, that's performance and can be tackled later. Will close this.

**Comment by gaelforget** [comment]
> Yes, absolutely, I guess the `P::NamedTuple` is purely a performance issue. I believe that growing the `I.🔴` (that's a DataFrame, right?) inside `∫!` is another bottleneck that one may want to come by. When I created the ShalloWaters example, IndividualDisplacements took about as long as running ShallowWaters -- which shouldn't be the case, I believe. Pre-allocating the memory might already be a big winner there.

Thanks for this feedback. Will do more benchmarking on this. The data frame (I.🔴), related allocations and 
diagnostic computations that go into it might indeed be the culprit. The `P::NamedTuple` has been turned into a struct (FlowFields) so we might be all set on that side. 

Anyway, thanks again, and please dont hesitate to reopen later if needed or open a new issue
