### ISSUE TITLE
u,v same eltype as time?

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#65]
Just a minor, but I get an
```julia
julia> F = 𝐹_Array2D(u,u,v,v,[0.,10.])
ERROR: MethodError: no method matching 𝐹_Array2D(::Array{Float32,2}, ::Array{Float32,2}, ::Array{Float32,2}, ::Array{Float32,2}, ::Array{Float64,1})
```
where I expect time `T::Array{Real,1}` or just an `AbstractVector` ?

**Comment by gaelforget** [comment]
This is now done, along with the bounds check in the `FlowFields` methods I just added in https://github.com/JuliaClimate/IndividualDisplacements.jl/pull/68

closed issue?

**Comment by milankl** [comment]
Great work!
