### ISSUE TITLE
Size check for input u,v

### ISSUE THREAD

**Issue by milankl** [JuliaClimate/IndividualDisplacements.jl#66]
https://github.com/JuliaClimate/IndividualDisplacements.jl/blob/ee63f6c480e858383116a54d6f8ca8044b72c854/src/API.jl#L38-L44

I'd suggest to have a boundscheck here, when I use u as an array of shape (nx-1) x ny and v of shape nx x (ny-1) so for example u 99x100 and v 100x99 this can hit

```julia
julia> ∫!(I)
ERROR: BoundsError: attempt to access 100×99 Array{Float64,2} at index [97, 100]
```

**Comment by milankl** [comment]
Alternatively, you may assume periodic boundary conditions or solid walls (i.e. pad u,v with zeros first)? I don't know how you handle this here, but for example with ShallowWaters.jl I scale the timestep of the semi-Lagrangian advection with the max expected velocity to guarantee that the interpolation scheme never attemps to access outside the array bounds. You probably know many ways to do this, but I think it would be great to either catch those errors early and/or make some assumptions to guarantee that they these boundserrors don't occur

**Comment by milankl** [comment]
Sorry, I believe BC are biperiodic by default? Checking against ShallowWaters.jl this looks good otherwise
![image](https://user-images.githubusercontent.com/25530332/110961260-80b20880-8347-11eb-9a57-5cfaf902bf76.png)

**Comment by gaelforget** [comment]
> Sorry, I believe BC are biperiodic by default? Checking against ShallowWaters.jl this looks good otherwise

yes -- biperiodic by default. Also true in the case of `MeshArray`s (v `Array`s) although periodicity is more elaborate for grids like cube spheres etc.

**Comment by gaelforget** [comment]
> Alternatively, you may assume periodic boundary conditions or solid walls (i.e. pad u,v with zeros first)? I don't know how you handle this here, but for example with ShallowWaters.jl I scale the timestep of the semi-Lagrangian advection with the max expected velocity to guarantee that the interpolation scheme never attemps to access outside the array bounds. You probably know many ways to do this, but I think it would be great to either catch those errors early and/or make some assumptions to guarantee that they these boundserrors don't occur

That's what `location_is_out` and `update_location!`  deal with in the case of `MeshArray`s. For plain `Array`s I just use `mod()`. Please refer to `src/compute.jl` (e.g. `dxy_dt!` and `dxy_dt`)

ps. `dxy_dt!` and `dxy_dt` have become confusing -- should probably be renamed as `dxy_dt_MeshArray` and `dxy_dt_Array` or something like that

**Comment by gaelforget** [comment]
> `dxy_dt!` and `dxy_dt` have become sort of confusing over course of revising code. Should probably be renamed as `dxy_dt_MeshArray`, `dxy_dt_Array`, etc or just `dxdt!` across the board

I did rename all as `dxdt!` in https://github.com/JuliaClimate/IndividualDisplacements.jl/pull/68

**Comment by gaelforget** [comment]
can close issue?

**Comment by milankl** [comment]
Yes, amazing, great work on all of this!
